package com.finalproject.ecommerce.ecommerce.shared.interfaces.rest.dto;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

@DisplayName("ErrorResponse Tests")
class ErrorResponseTest {

    @Test
    @DisplayName("Should create ErrorResponse with all fields using full constructor")
    void shouldCreateErrorResponseWithAllFields() {
        LocalDateTime timestamp = LocalDateTime.now();

        ErrorResponse errorResponse = new ErrorResponse(
                400,
                "Bad Request",
                "Invalid input data",
                timestamp,
                "/api/v1/products"
        );

        assertThat(errorResponse.getStatus()).isEqualTo(400);
        assertThat(errorResponse.getMessage()).isEqualTo("Bad Request");
        assertThat(errorResponse.getDetails()).isEqualTo("Invalid input data");
        assertThat(errorResponse.getTimestamp()).isEqualTo(timestamp);
        assertThat(errorResponse.getPath()).isEqualTo("/api/v1/products");
    }

    @Test
    @DisplayName("Should create ErrorResponse with auto-generated timestamp using partial constructor")
    void shouldCreateErrorResponseWithAutoGeneratedTimestamp() {
        LocalDateTime before = LocalDateTime.now();

        ErrorResponse errorResponse = new ErrorResponse(
                404,
                "Not Found",
                "Product with ID 123 not found",
                "/api/v1/products/123"
        );

        LocalDateTime after = LocalDateTime.now();

        assertThat(errorResponse.getStatus()).isEqualTo(404);
        assertThat(errorResponse.getMessage()).isEqualTo("Not Found");
        assertThat(errorResponse.getDetails()).isEqualTo("Product with ID 123 not found");
        assertThat(errorResponse.getPath()).isEqualTo("/api/v1/products/123");
        assertThat(errorResponse.getTimestamp()).isNotNull();
        assertThat(errorResponse.getTimestamp()).isBetween(before, after);
    }

    @Test
    @DisplayName("Should create ErrorResponse using no-args constructor")
    void shouldCreateErrorResponseUsingNoArgsConstructor() {
        ErrorResponse errorResponse = new ErrorResponse();

        assertThat(errorResponse).isNotNull();
        assertThat(errorResponse.getStatus()).isZero();
        assertThat(errorResponse.getMessage()).isNull();
        assertThat(errorResponse.getDetails()).isNull();
        assertThat(errorResponse.getTimestamp()).isNull();
        assertThat(errorResponse.getPath()).isNull();
    }

    @Test
    @DisplayName("Should support setters for all fields")
    void shouldSupportSettersForAllFields() {
        ErrorResponse errorResponse = new ErrorResponse();
        LocalDateTime timestamp = LocalDateTime.now();

        errorResponse.setStatus(500);
        errorResponse.setMessage("Internal Server Error");
        errorResponse.setDetails("Database connection failed");
        errorResponse.setTimestamp(timestamp);
        errorResponse.setPath("/api/v1/orders");

        assertThat(errorResponse.getStatus()).isEqualTo(500);
        assertThat(errorResponse.getMessage()).isEqualTo("Internal Server Error");
        assertThat(errorResponse.getDetails()).isEqualTo("Database connection failed");
        assertThat(errorResponse.getTimestamp()).isEqualTo(timestamp);
        assertThat(errorResponse.getPath()).isEqualTo("/api/v1/orders");
    }

    @Test
    @DisplayName("Should create ErrorResponse for validation error")
    void shouldCreateErrorResponseForValidationError() {
        ErrorResponse errorResponse = new ErrorResponse(
                400,
                "Validation Failed",
                "Email format is invalid",
                "/api/v1/users/register"
        );

        assertThat(errorResponse.getStatus()).isEqualTo(400);
        assertThat(errorResponse.getMessage()).isEqualTo("Validation Failed");
        assertThat(errorResponse.getDetails()).contains("Email format");
        assertThat(errorResponse.getTimestamp()).isCloseTo(
                LocalDateTime.now(),
                within(1, ChronoUnit.SECONDS)
        );
    }

    @Test
    @DisplayName("Should create ErrorResponse for unauthorized access")
    void shouldCreateErrorResponseForUnauthorizedAccess() {
        ErrorResponse errorResponse = new ErrorResponse(
                401,
                "Unauthorized",
                "Invalid or expired token",
                "/api/v1/carts"
        );

        assertThat(errorResponse.getStatus()).isEqualTo(401);
        assertThat(errorResponse.getMessage()).isEqualTo("Unauthorized");
        assertThat(errorResponse.getDetails()).isEqualTo("Invalid or expired token");
    }

    @Test
    @DisplayName("Should create ErrorResponse for forbidden access")
    void shouldCreateErrorResponseForForbiddenAccess() {
        ErrorResponse errorResponse = new ErrorResponse(
                403,
                "Forbidden",
                "You don't have permission to access this resource",
                "/api/v1/admin/products"
        );

        assertThat(errorResponse.getStatus()).isEqualTo(403);
        assertThat(errorResponse.getMessage()).isEqualTo("Forbidden");
        assertThat(errorResponse.getPath()).isEqualTo("/api/v1/admin/products");
    }

    @Test
    @DisplayName("Should create ErrorResponse for resource conflict")
    void shouldCreateErrorResponseForResourceConflict() {
        ErrorResponse errorResponse = new ErrorResponse(
                409,
                "Conflict",
                "User with email test@example.com already exists",
                "/api/v1/users"
        );

        assertThat(errorResponse.getStatus()).isEqualTo(409);
        assertThat(errorResponse.getMessage()).isEqualTo("Conflict");
        assertThat(errorResponse.getDetails()).contains("already exists");
    }

    @Test
    @DisplayName("Should create ErrorResponse for empty cart error")
    void shouldCreateErrorResponseForEmptyCartError() {
        ErrorResponse errorResponse = new ErrorResponse(
                400,
                "Invalid request or cart is empty",
                "Cart with ID 123 is empty",
                "/api/v1/orders"
        );

        assertThat(errorResponse.getStatus()).isEqualTo(400);
        assertThat(errorResponse.getMessage()).isEqualTo("Invalid request or cart is empty");
        assertThat(errorResponse.getDetails()).isEqualTo("Cart with ID 123 is empty");
        assertThat(errorResponse.getPath()).isEqualTo("/api/v1/orders");
    }

    @Test
    @DisplayName("Should support equals and hashCode")
    void shouldSupportEqualsAndHashCode() {
        LocalDateTime timestamp = LocalDateTime.now();
        ErrorResponse error1 = new ErrorResponse(400, "Bad Request", "Details", timestamp, "/api/test");
        ErrorResponse error2 = new ErrorResponse(400, "Bad Request", "Details", timestamp, "/api/test");
        ErrorResponse error3 = new ErrorResponse(404, "Not Found", "Details", timestamp, "/api/test");

        assertThat(error1).isEqualTo(error2);
        assertThat(error1).isNotEqualTo(error3);
        assertThat(error1.hashCode()).isEqualTo(error2.hashCode());
    }

    @Test
    @DisplayName("Should have proper toString representation")
    void shouldHaveProperToStringRepresentation() {
        ErrorResponse errorResponse = new ErrorResponse(
                500,
                "Server Error",
                "Unexpected error occurred",
                "/api/v1/test"
        );

        String toString = errorResponse.toString();

        assertThat(toString).contains("status=500");
        assertThat(toString).contains("message=Server Error");
        assertThat(toString).contains("details=Unexpected error occurred");
        assertThat(toString).contains("path=/api/v1/test");
    }

    @Test
    @DisplayName("Should handle null values gracefully")
    void shouldHandleNullValuesGracefully() {
        ErrorResponse errorResponse = new ErrorResponse(
                400,
                null,
                null,
                null
        );

        assertThat(errorResponse.getStatus()).isEqualTo(400);
        assertThat(errorResponse.getMessage()).isNull();
        assertThat(errorResponse.getDetails()).isNull();
        assertThat(errorResponse.getPath()).isNull();
        assertThat(errorResponse.getTimestamp()).isNotNull();
    }

    @Test
    @DisplayName("Should create ErrorResponse for rate limit exceeded")
    void shouldCreateErrorResponseForRateLimitExceeded() {
        ErrorResponse errorResponse = new ErrorResponse(
                429,
                "Too Many Requests",
                "Rate limit exceeded. Please try again later.",
                "/api/v1/products"
        );

        assertThat(errorResponse.getStatus()).isEqualTo(429);
        assertThat(errorResponse.getMessage()).isEqualTo("Too Many Requests");
        assertThat(errorResponse.getDetails()).contains("Rate limit exceeded");
    }

    @Test
    @DisplayName("Should create ErrorResponse for service unavailable")
    void shouldCreateErrorResponseForServiceUnavailable() {
        ErrorResponse errorResponse = new ErrorResponse(
                503,
                "Service Unavailable",
                "Payment service is temporarily unavailable",
                "/api/v1/payments"
        );

        assertThat(errorResponse.getStatus()).isEqualTo(503);
        assertThat(errorResponse.getMessage()).isEqualTo("Service Unavailable");
        assertThat(errorResponse.getDetails()).contains("temporarily unavailable");
    }

    @Test
    @DisplayName("Should timestamp be close to creation time")
    void shouldTimestampBeCloseToCreationTime() {
        LocalDateTime before = LocalDateTime.now();

        ErrorResponse errorResponse = new ErrorResponse(
                400,
                "Test Error",
                "Test Details",
                "/api/test"
        );

        LocalDateTime after = LocalDateTime.now();

        assertThat(errorResponse.getTimestamp())
                .isAfterOrEqualTo(before)
                .isBeforeOrEqualTo(after);
    }

    @Test
    @DisplayName("Should create different timestamps for different instances")
    void shouldCreateDifferentTimestampsForDifferentInstances() throws InterruptedException {
        ErrorResponse error1 = new ErrorResponse(400, "Error 1", "Details 1", "/api/1");
        Thread.sleep(10);
        ErrorResponse error2 = new ErrorResponse(400, "Error 2", "Details 2", "/api/2");

        assertThat(error1.getTimestamp()).isNotNull();
        assertThat(error2.getTimestamp()).isNotNull();
        assertThat(error2.getTimestamp()).isAfterOrEqualTo(error1.getTimestamp());
    }

    @Test
    @DisplayName("Should handle empty strings")
    void shouldHandleEmptyStrings() {
        ErrorResponse errorResponse = new ErrorResponse(
                400,
                "",
                "",
                ""
        );

        assertThat(errorResponse.getMessage()).isEmpty();
        assertThat(errorResponse.getDetails()).isEmpty();
        assertThat(errorResponse.getPath()).isEmpty();
    }

    @Test
    @DisplayName("Should create ErrorResponse for business rule violation")
    void shouldCreateErrorResponseForBusinessRuleViolation() {
        ErrorResponse errorResponse = new ErrorResponse(
                422,
                "Unprocessable Entity",
                "Cannot delete product that has pending orders",
                "/api/v1/products/456"
        );

        assertThat(errorResponse.getStatus()).isEqualTo(422);
        assertThat(errorResponse.getMessage()).isEqualTo("Unprocessable Entity");
        assertThat(errorResponse.getDetails()).contains("Cannot delete product");
    }
}

